### ISSUE TITLE
a conflict exception occur when shrinkResources is open

### ISSUE THREAD

**Issue by chenzhu33** [BryanSharp/hibeaver#10]
Error:Execution failed for task ':ime:transformClassesWithShrinkResForMainLineReleaseKlog'.
> class com.android.build.gradle.tasks.ResourceUsageAnalyzer$UsageVisitor has interface org.objectweb.asm.ClassVisitor as super class

**Comment by BryanSharp** [comment]
the reason of this exp has been figured out, which is version conflict of ASM between android gradle plugin and hibeaver plugin. Now I'm trying to solve it.

**Comment by chenzhu33** [comment]
It seems that updating the asm version from 3.3 to 5.X can solve this problem.

**Comment by BryanSharp** [comment]
exactly. In 5.x ClassVisitor is a Class, and in 3.x it is an interface, which causes the log output you mentioned:

> class XXX has interface org.objectweb.asm.ClassVisitor as super class

In 1.2.5 this bug has been fixed.
