### ISSUE TITLE
可否实现对实现接口匿名内部类的支持

### ISSUE THREAD

**Issue by violinday** [BryanSharp/hibeaver#19]
btn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                       //TODO 再次插入代码
                    }
                });

**Comment by BryanSharp** [comment]
这个应该是支持的 接口匿名内部类的类名就是 主全类名$数字
比如如果是com.test.MainActivity的第一个匿名内部类 其类名就是
com.test.MainActivity$1
可以试下

**Comment by violinday** [comment]
@BryanSharp  好的，谢谢啦。我试试去
