### ISSUE TITLE
博主你好，如果activity本身没重写onResume方法的话，要怎么拦截呢

### ISSUE THREAD

**Issue by wudicsy** [BryanSharp/hibeaver#20]
正在做一个针对控制activity和fragment生命周期的项目

**Comment by BryanSharp** [comment]
你如果使用了v4兼容包，所有的Activity类都继承了v4包中的AppCompatActivity或者FragmentActivity，那么就可以修改这个父类的onResume。核心思路还是通过父类找到target方法。没有可修改的target方法肯定不行。
