### ISSUE TITLE
Conflict with realm transform

### ISSUE THREAD

**Issue by hufozhu** [BryanSharp/hibeaver#21]
Hi, 

Hibeaver will run into a error when the project uses realm, maybe you can help to ignore the error or add folder ignore config. Thanks.

This is the log:
![image](https://user-images.githubusercontent.com/1925674/29459389-ec8d63a0-8455-11e7-9e2e-e1edbd31fb25.png)

**Comment by BryanSharp** [comment]
will test and find a way to tackle this.
